-- Copyright (c) 2025 Meta Games, LLC. All rights reserved.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Packages = ReplicatedStorage:WaitForChild("Packages")
local require = require(Packages:WaitForChild("knight")).require

local <filename> = {}
<filename>.__index = <filename>

function <filename>:init()
    return
end

function <filename>:start()
    return
end

return <filename>
